### ISSUE TITLE
Don't print .DS_Store in list

### ISSUE THREAD

**Issue by ColinFay** [r-lib/rim#36]
Hey, 

Thanks a lot for `rim`! That was much needed, awesome. 

On mac, I think `rim list` shouldn't print .DS_Store? 

```
colin$ rim list
.DS_Store
3.4
3.6
4.1
4.2
```

**Comment by gaborcsardi** [comment]
Yeah, it will cause other issues as well, so I suggest you remove it, until rim learns to deal with it.
