### ISSUE TITLE
[feature request] rim start 

### ISSUE THREAD

**Issue by ColinFay** [r-lib/rim#37]
It would be nice to be able to start specific versions of R, instead of switching from one to the other with `default`.

For example, instead of

```
rim default 4.2.0
R
# [... try the new version...]
q()
rim default 4.1.2
R
# [... get back to where I was at...]
```

It would be cool to be able to do: 

```
rim start 4.1.2
# [... try the new version...]
q()
# [... still have the default version...]
```

**Comment by gaborcsardi** [comment]
rim makes links, so you can call `R-4.1`, `R-4.1-arm64`, etc.

#29 might be a duplicate?

**Comment by gaborcsardi** [comment]
Btw. the good thing with the `R-4.1` etc. links, is that they never change the default version, and they can run in parallel. (This is if you install all R versions with rim, or call `rim system make-orthogonal`.)
