### ISSUE TITLE
points to default r version?

### ISSUE THREAD

**Issue by ShixiangWang** [r-lib/rim#38]
A nice tool I never imaged!

I have a suggestion here.

```sh
C:\Users\Administrator>rim list
4.1.2
4.1.3
```

When `4.1.3` set as default, adding a mark may be more readable, so no need to call `rim default`.

```sh
C:\Users\Administrator>rim list
4.1.2
4.1.3 (default)
```

Also, I just tried the rim, I found after I install the `4.1.3`, the RStudio use `4.1.3` already, however, `rim` did not point `4.1.3` or `4.1.2` as default. I don't know if they should be consistent.

**Comment by gaborcsardi** [comment]
This is now implemented and in 0.3.0.
