### ISSUE TITLE
Some questions on the `R-*` quick links that get added

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rim#41]
I had a few questions about the quick links that got installed when I did `rim add release`. I will refer back to the results of `rim list`, so here is that for now:

```
$ rim list
.DS_Store
3.3
3.6
4.0
4.1
4.2
```

1. (Ah, this is #36) What is up with the `.DS_Store` one? It shows up in `rim list` and I get:

```
Adding /usr/local/bin/R-.DS_Store -> /Library/Frameworks/R.framework/Versions/.DS_Store/Resources/bin/R
```

<img width="982" alt="Screen Shot 2022-04-20 at 5 42 35 PM" src="https://user-images.githubusercontent.com/19150088/164327775-efb47472-4061-400b-9884-f97cdd89d2b3.png">

2. Why does R-4.0 get added and then removed?

```
Adding /usr/local/bin/R-4.0 -> /Library/Frameworks/R.framework/Versions/4.0/Resources/bin/R
...
Cleaning up /Library/Frameworks/R.framework/Versions/4.0/Resources/bin/R
```

3. Why do all quick links link to R 4.1.3? Look at the opened version of R here. 

<img width="477" alt="Screen Shot 2022-04-20 at 5 45 10 PM" src="https://user-images.githubusercontent.com/19150088/164328132-a8befd97-dc91-4996-a3d2-f76a10b5506f.png">

**Comment by DavisVaughan** [comment]
Okay well I can answer all of these after some further investigation.

1. This is #36 and I just deleted the file
2. My 4.0 install is apparently very broken. this is probably when I was toying with building r-devel locally or something (it is a nearly empty folder)
<img width="425" alt="Screen Shot 2022-04-20 at 6 01 46 PM" src="https://user-images.githubusercontent.com/19150088/164332591-2799127b-4635-429a-a7d2-5a7c3ab78c08.png">

**Comment by gaborcsardi** [comment]
> I don't know why, but things like /Library/Frameworks/R.framework/Versions/3.6/Resources/bin/R DO actually just open R 4.1.3 for me?? So, probably not a rim thing?

If a link opens the wrong version, that's probably because not all versions were installed by rim, so they are not orthogonal. We could do a better job with this, though, e.g. just call `rim system make-orthogonal`.
