### ISSUE TITLE
ERROR: no permission to install to directory

### ISSUE THREAD

**Issue by julianhinz** [r-lib/rim#80]
Fresh install of `rig` on MacOS 12.4 on Apple Silicon. Can't install any packages:

```r

> install.packages("data.table")
Installing package into ‘/Users/abc/Library/R/arm64/4.2/library’
(as ‘lib’ is unspecified)
Warning in install.packages("data.table") :
  'lib = "/Users/abc/Library/R/arm64/4.2/library"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) y
trying URL 'https://cran.rstudio.com/src/contrib/data.table_1.14.2.tar.gz'
Content type 'application/x-gzip' length 5301817 bytes (5.1 MB)
==================================================
downloaded 5.1 MB

Error: ERROR: no permission to install to directory ‘/Users/abc/Library/R/arm64/4.2/library’

The downloaded source packages are in
	‘/private/var/folders/yx/zy96k6jn0w313_zbnc8v6ny00000gn/T/Rtmp53WMO0/downloaded_packages’
Warning message:
In install.packages("data.table") :
  installation of package ‘data.table’ had non-zero exit status
> 

```

Any hints?

**Comment by gaborcsardi** [comment]
rig forces you to use user libraries, and you don't have a user library on this R version. rig creates this library for the R versions it installs, but not for the others. I guess you installed 4.2-arm before rig. 

To set up the user libraries for all installed versions run
```
rig system setup-user-lib
```

**Comment by gaborcsardi** [comment]
Yeah, this is actually a rig bug, it creates that library right after installing R, as root, when it is installing pak: #84 Will fix this ASAP!

**Comment by gaborcsardi** [comment]
Should be fixed by #92.

**Comment by julianhinz** [comment]
Works perfectly now in 0.5, thanks!

**Comment by luceydav** [comment]
I think I'm having a similar problem on my new M1 install. I ran "rig system setup-user-lib", this is what happens when I try to install the release. 

<img width="857" alt="Screen Shot 2022-10-08 at 5 33 59 AM" src="https://user-images.githubusercontent.com/19495240/194701036-a312996c-bde9-411d-8f03-d1a4f384dac8.png">

**Comment by gaborcsardi** [comment]
Is it possible that that library was created with an older version of rig? Current rig should not do this anymore.

A workaround is to fix the permissions manually.

**Comment by luceydav** [comment]
This is Rig 0.5.2 installed with Homebrew 3.6.4 for arm64 (not Rosetta). I was able to  figure out by first installing rig as above, then changing admin permissions for the library folder to Read & Write from Read, then rig system add-pak. Is this safe permissioning going forward?

**Comment by gaborcsardi** [comment]
Yes, it is a one time fix.
